# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- gem i slather --no-ri --no-rdoc
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Collor.xcworkspace -scheme Collor-Example -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty
- pod lib lint --allow-warnings
after_success: 
- slather
